// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type SeatStatus struct {
	RowNumber  int32  `json:"rowNumber"`
	SeatLetter string `json:"seatLetter"`
	Occupied   bool   `json:"occupied"`
}

type Subscription struct {
}
